import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import './global.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className='layout'>
          <Header />
          <main className='content'>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
