import { Header } from '@/components/Header/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{height: '100%', margin: 0}}>
      <body  style={{height: '100%', margin: 0}}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
